config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'static_pages#home', as:'home'
  get '/contact', to: 'static_pages#contact'
  get '/about', to: 'static_pages#about'

  get '/about/me', to: 'static_pages#about_me', as:'about_me'
  get '/about/myteam', to: 'static_pages#about_my_team', as:'about_my_team'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end

  def me
  end

  def myteam
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JeMePresente</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"/>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/about_me.html.erb
<center><h1>Présentation 👌🏻 </h1> </center>
<hr>
<p> Je m'appelle Moog et la vie est belle 👌</p>


<div><%= link_to "home" , home_path %></div>

app/views/static_pages/about_my_team.html.erb
<center> <h1>My THP Team 👌🏻</h1> </center>
<hr>
<ul>

	<li><%= link_to "Eang Ly ENG" , about_me_path %> </li>
    <li>Kwevan GOUACIDE </li>
    <li>Jérémie EDERY</li>
    <li>Amélie FOULQUIER</li>
    <li>Stéphane RABENARISOA</li>
    <li>Rémi BOIVIN</li>
</ul>


<%= link_to "home" , home_path %>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
<center>
<h1> Bienvenue sur mon beau site 👌🏻  </h1>
</center>
<hr>

<%= link_to "about ME" , about_me_path %> </br>
<%= link_to "about MY TEAM " , about_my_team_path %>